baseURL = "http://localhost:1313/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Jian"                         # site title  # 网站标题
theme = "jian"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                           # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id
disqusShortname = ""                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

canonifyURLs = true

[author]                               # essential # 必需
  name = "you"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu  # 配置菜单
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "the site subtitle"                                       # site's subTitle  # 网站二级标题
  footerSlogan = "My footer slogan"                                   # site's footer slogan  # 网站页脚标语
  keywords = ["Hugo","theme","jian"]                                  # site's keywords  # 网站关键字
  description = "Hugo theme jian example site."                        # site's description  # 网站描述
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  # title404 = ""
  mainSections = ["posts","post"]

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = "<your-id>"
  appKey = "<your-key>"
  placeholder = "input comment..."
  visitor = true

# Your socail's url
[social]
  github = "http://github.com/[username]"
  twitter = "http://twitter.com/[username]"
  facebook = "http://facebook.com/[username]"
  weibo = "http://weibo.com/[username]"
  instagram = "https://www.instagram.com/[username]"

# ref : https://gohugo.io/getting-started/configuration-markup#highlight
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

# googleAnalytics = "UA-123-45"

